---
- hosts: all
  sudo: true

  tasks:
    - lineinfile: dest=/etc/rc.local  line="echo never > /sys/kernel/mm/transparent_hugepage/defrag" state=present

    - lineinfile: dest=/etc/rc.local  line="echo never > /sys/kernel/mm/transparent_hugepage/enabled" state=present

    - shell: echo never > /sys/kernel/mm/transparent_hugepage/defrag

    - shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled

    # Immediately avaiable
    - shell: sysctl -w vm.swappiness=10
        
    - shell: sysctl -w kernel.pid_max=2000000
        
    - shell: sysctl -w kernel.threads-max=2000000

    # Persists in the file /etc/sysctl.conf
    - name: Set vm.swappiness=10 
      sysctl: name=vm.swappiness value=10 state=present reload=yes

    - name: Set kernel.pid_max=2000000
      sysctl: name=kernel.pid_max value=2000000 state=present reload=yes


    - name: Set kernel.threads-max=2000000
      sysctl: name=kernel.threads-max value=2000000 state=present reload=yes
          
    - name: Update nofile /etc/security/limits.conf
      lineinfile: dest=/etc/security/limits.conf  line="{{item}} - nofile 65536" state=present 
      with_items:
              - hdfs
              - mapred
              - hive
              - hbase
              - impala
              - yarn
              - zookeeper
              - spark
                 

    - name: Update nproc /etc/security/limits.conf
      lineinfile: dest=/etc/security/limits.conf  line="{{item}} - nproc unlimited" state=present 
      with_items:
              - hdfs
              - mapred
              - hive
              - hbase
              - impala
              - yarn
              - zookeeper
              - spark
