---
- hosts: all
  serial: 1
  any_errors_fatal: true
  gather_facts: false
  sudo: yes

  tasks:

    - name: Uninstall cm agent
      yum:
         name: cloudera-manager-agent
         state: absent
      tags:
         - uninstall_current_cm_agent
 
    - name: Uninstall cm agent daemons
      yum:
         name: cloudera-manager-daemons
         state: absent
      tags:
         - uninstall_current_cm_agent_daemons

    - name: Copy RHEL-7 repofile
      copy:
         src: files/cloudera-manager.repo
         dest: /etc/yum.repos.d/cloudera-manager.repo
         owner: root
         group: root
      tags:
         - copy_cloudera_repofile_rhel7
 
    - name: yum clean all
      command: yum clean all
      tags:
         - yum_clean_cache

    - name: Install cm 15.5.1 agent
      yum:
         name: cloudera-manager-agent
         state: present
      tags:
         - install_cm_agent
 
    - name: Install cm 15.5.1 agent daemons
      yum:
         name: cloudera-manager-daemons
         state: present
      tags:
         - install_cm_agent_daemons

# Run this task only on CM Server
    - name: Install cm 15.5.1 server
      yum:
         name: cloudera-manager-server
         state: present
      tags:
         - install_cm_server

    - name: Copy config.ini file
      template: src=templates/{{ item }}.j2 dest=/etc/cloudera-scm-agent/config.ini owner=root group=root mode=0644 backup=yes
      with_items:
          - "config.ini"
      tags:
         - copy_config_ini_file

    - name: Start CM Agent
      command: systemctl start cloudera-scm-agent 
      tags:
         - start_cm_agent

    - name: Check status of CM Agent after restart
      command: systemctl status cloudera-scm-agent 
      tags:
         - chk_cmagent_after_restart
